= 2. General Information

* This chapter covers information that is relevant to all the functions
  specified in System Interfaces and XBD Headers.

== 2.2 The Compilation Environment

=== 2.2.1 POSIX.1 Symbols

* Certain symbols in this volume of POSIX.1-2017 are defined in headers (see
  XBD Headers).
* Some of those headers could also define symbols other than those defined by
  POSIX.1-2017, potentially conflicting with symbols used by the application.
* Also, POSIX.1-2017 defines symbols that are not permitted by other standards
  to appear in those headers without some control on the visibility of those
  symbols.

'''

* Symbols called "feature test macros" are used to control the visibility of
  symbols that might be included in a header.
* Implementations, future versions of this standard, and other standards may
  define additional feature test macros.

'''

* In the compilation of an application that **#define**s a feature test macro
  specified by POSIX.1-2017, no header defined by POSIX.1-2017 shall be
  included prior to the definition of the feature test macro.
* This restriction also applies to any implementation-provided header in which
  these feature test macros are used.
* If the definition of the macro does not precede the #include, the result is
  undefined.

* Feature test macros shall begin with the <underscore> character ('_').

==== The _POSIX_C_SOURCE Feature Test Macro

* A POSIX-conforming application shall ensure that the feature test macro
  _POSIX_C_SOURCE is defined before inclusion of any header.

'''

* When an application includes a header described by POSIX.1-2017, and when
  this feature test macro is defined to have the value 200809L:
1. All symbols required by POSIX.1-2017 to appear when the header is included
   shall be made visible.
2. Symbols that are explicitly permitted, but not required, by POSIX.1-2017 to
   appear in that header (including those in reserved name spaces) may be made
   visible.
3. Additional symbols not required or explicitly permitted by POSIX.1-2017 to
   be in that header shall not be made visible, except when enabled by another
   feature test macro.

'''

* Identifiers in POSIX.1-2017 may only be undefined using the *#undef* directive
  as described in Use and Implementation of Interfaces or The Name Space.
* These *#undef* directives shall follow all *#include* directives of any
  header in POSIX.1-2017.

[NOTE]
====
* The POSIX.1-1990 standard specified a macro called _POSIX_SOURCE.
* This has been superseded by _POSIX_C_SOURCE.
====

=== 2.2.2 The Name Space

* All identifiers in this volume of POSIX.1-2017, except environ, are defined
  in at least one of the headers, as shown in XBD Headers.
* When _POSIX_C_SOURCE is defined, each header defines or declares some
  identifiers, potentially conflicting with identifiers used by the
  application.
* The set of identifiers visible to the application consists of precisely
  those identifiers from the header pages of the included headers, as well as
  additional identifiers reserved for the implementation.
* In addition, some headers may make visible identifiers from other headers as
  indicated on the relevant header pages.

'''

* Implementations may also add members to a structure or union without
  controlling the visibility of those members with a feature test macro, as
  long as a user-defined macro with the same name cannot interfere with the
  correct interpretation of the program.
* The identifiers reserved for use by the implementation are described below:
1. Each identifier with external linkage described in the header section is
   reserved for use as an identifier with external linkage if the header is
   included.
2. Each macro described in the header section is reserved for any use if the
   header is included.
3. Each identifier with file scope described in the header section is reserved
   for use as an identifier with file scope in the same name space if the
   header is included.

* The prefixes posix_, POSIX_, and \_POSIX_ are reserved for use by
  POSIX.1-2017 and other POSIX standards.
* Implementations may add symbols to the headers shown in the following table,
  provided the identifiers for those symbols either:
1. Begin with the corresponding reserved prefixes in the table, or
2. Have one of the corresponding complete names in the table, or
3. End in the string indicated as a reserved suffix in the table and do not
   use the reserved prefixes posix_, POSIX_, or \_POSIX_, as long as the
   reserved suffix is in that part of the name considered significant by the
   implementation.

* Symbols that use the reserved prefix \_POSIX_ may be made visible by
  implementations in any header defined by POSIX.1-2017.

[%autowidth]
|===
|Header		|Suffix

|<limits.h>	|_MAX, _MIN
|===
